version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm ci
          when: always

      - run:
          name: Run Linter
          command: npm run lint

      - run:
          name: Run cypress tests process
          command: npm run test

      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: cypress/videos

      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: cypress/screenshots

      - store_artifacts:
          name: Uploading report artifacts
          path: cypress/reports/finalReports
