version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    
    steps:
      - checkout
      
      
      - run:
          name: Install Dependencies
          command: npm ci
          when: always
     
      - run:
          name: Run cypress pretests
          command: npm run pretest

      - run:
          name: Run cypress tests
          command: npm run scripts

      - run:
          name: Run combine reports
          command: npm run combine-reports

      - run:
          name: Run generate reports
          command: npm run generate-report
     
      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: cypress/videos

      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: cypress/screenshots

      - store_artifacts:
          name: Uploading report artifacts
          path: reports
