# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: execute pipeline
on:
  push:
     branches:
      - 'main'
      
jobs:
    cypress-test:
      name: Run on Chrome 94
      runs-on: ubuntu-18.04
      container: cypress/browsers:node16.5.0-chrome94-ff93
      steps:
        - uses: actions/checkout@v2
        
        - name: Install Cypress and verify
          run: |
            npm ci
            $(npm bin)/cypress verify
            
            
        - name: Run Cypress Test
          run: npm run test
          continue-on-error: false
          
        - name: Copy test execution videos and screenshots
          run: |
            mkdir public
            cp -r cypress/videos public/videos
            cp -r cypress/screenshots public/screenshots
            
        - name: Deploy report page to github
          uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./public
